name: build-windows
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: checkout code
        uses: actions/checkout@v7

      - name: install dependencies
        run: |
        pacman -S mingw-w64-ucrt-x86_64-gtk4 mingw-w64-ucrt-x86_64-libadwaita \
        mingw-w64-ucrt-x86_64-fontconfig mingw-w64-ucrt-x86_64-libsoup3 \
        mingw-w64-ucrt-x86_64-libcurl mingw-w64-ucrt-x86_64-json-glib \
        mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-cmake \
        mingw-w64-ucrt-x86_64-make \
        mingw-w64-ucrt-x86_64-nlohmann-json

      - name: build
        run: |
          cmake -B build -G "MinGW Makefiles" \
            -DCMAKE_MAKE_PROGRAM=mingw32-make \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_BUILD_TYPE=Release .
          cmake --build build --parallel $(nproc)

      - name: upload release
        uses: actions/upload-artifact@v7
        with:
          name: PCL-CGRE-windows
          path: build/pcl-cgre.exe
